# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    cours_documents_directory: '%kernel.project_dir%/var/uploads/documents'
    groq_url: '%env(string:GROQ_URL)%'
    groq_model: '%env(string:GROQ_MODEL)%'
    app.groq_api_key: '%env(string:GROQ_API_KEY)%'
    profanity_api_url: '%env(string:PROFANITY_API_URL)%'
    profanity_api_host: '%env(string:PROFANITY_API_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\GeminiService:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Service\ReCaptchaService:
        arguments:
            $secretKey: '%env(RECAPTCHA3_SECRET)%'
            $scoreThreshold: 0.5
            $enabled: false

    App\Service\Investment\InvestmentChatbotService:
        arguments:
            $hfToken: '%env(HF_TOKEN)%'
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Service\Investment\StripePaymentService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\Investment\ContractQrCodeService:
        arguments:
            $publicBaseUrl: '%env(string:APP_PUBLIC_URL)%'

    App\Service\AvisRatingService:
        arguments:
            $groqApiKey: '%env(string:GROQ_API_KEY)%'
            $groqUrl: '%groq_url%'
            $groqModel: '%groq_model%'

    App\Service\CoursQuizService:
        arguments:
            $groqApiKey: '%env(string:GROQ_API_KEY)%'
            $groqUrl: '%groq_url%'
            $groqModel: '%groq_model%'

    App\Service\ProfanityCheckService:
        arguments:
            $rapidApiKey: '%env(string:RAPIDAPI_KEY)%'
            $rapidApiHost: '%profanity_api_host%'
            $rapidApiUrl: '%profanity_api_url%'
